import './categories.css';
import './footer.css';
import './homepage.css';
import './categoriespropage.css'
import './navbar.css';
import './product.css';
import './Comment.css';
import './AdminPage.css';
import './QandA.css';
import './Gallery.css';
import './Search.css';
import './productpage.css';
import './Chat.css';
import './Microproduct.css'